server:
  port: 8081


spring:
  application:
    name: auth-service


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false


  flyway:
    enabled: false


jwt:
  private-key: ${JWT_PRIVATE_KEY_PATH:file:/app/keys/private.pem}
  public-key: ${JWT_PUBLIC_KEY_PATH:file:/app/keys/public.pem}
  expiration: ${JWT_EXPIRATION:3600000}


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

  endpoint:
    health:
      show-details: when_authorized


logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN