spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/medmatch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true


jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  expiration: 3600000