spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8081

rsa:
  private-key: ${RSA_PRIVATE_KEY_LOCATION:classpath:keys/private_key.pem}
  public-key: ${RSA_PUBLIC_KEY_LOCATION:classpath:keys/public_key.pem}