spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/medmatch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true


jwt:
  private-key: ${JWT_PRIVATE_KEY_PATH:classpath:keys/private.pem}
  public-key: ${JWT_PUBLIC_KEY_PATH:classpath:keys/public.pem}
  expiration: ${JWT_EXPIRATION:3600000}