apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: medmatch
  labels:
    app: medmatch
    component: postgres
    environment: production
spec:

  type: ClusterIP
  selector:
    app: medmatch
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432