apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medmatch

resources:
  - namespace.yaml

  - config/configmap.yaml
  - secrets/secrets.yaml

  - rbac/service-account.yaml
  - storage/storage-class.yaml

  - postgres/postgres-init.yaml
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml

  - redis/redis-statefulset.yaml
  - redis/redis-service.yaml

  - auth-service/deployment.yaml
  - auth-service/service.yaml

  - ai-service/deployment.yaml
  - ai-service/service.yaml

  - worker/deployment.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - network/network-policy.yaml

  - ingress.yaml
  - hpa.yaml

  - monitoring/servicemonitor.yaml

labels:
  - pairs:
      app: medmatch
      environment: production