apiVersion: v1
kind: Secret

metadata:
  name: medmatch-secret

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  DB_USER: postgres
  DB_PASSWORD: postgres

  GOOGLE_API_KEY: "<your-gemini-api-key>"

  JWT_PUBLIC_KEY_PATH: keys/public_key.pem

  RSA_PRIVATE_KEY_LOCATION: classpath:keys/private_key.pem
  RSA_PUBLIC_KEY_LOCATION: classpath:keys/public_key.pem