#!/usr/bin/env bash
#
# infra/scripts/deploy.sh
#
# Deployment sequence for MedMatch on Kubernetes.
#
# Ensures database migrations complete successfully BEFORE any
# long-running application pod (auth-service, ai-service,
# celery-worker) can start serving against a database that isn't
# ready or hasn't been migrated yet. Kubernetes/Kustomize have no
# manifest-level equivalent of Docker Compose's
# `condition: service_completed_successfully` for two independent
# Jobs, so that ordering is enforced here, procedurally, by this
# script.
#
# Design note: this applies the FULL kustomize build in one pass
# (namespace, ConfigMap, Secret, PostgreSQL, Redis, migration Jobs,
# and application Deployments together), rather than hand-splitting
# it into per-file `kubectl apply -f` calls. Applying the whole
# rendered manifest is what actually resolves the Flyway ConfigMap's
# generated, hash-suffixed name correctly inside the migration Jobs
# (verified with `kustomize build .` - see the deployment report);
# splitting it into individual file applies would either lose that
# resolved name or require re-implementing kustomize's own
# name-reference logic by hand, which is unnecessary risk for no
# benefit. Deployment pods existing before migrations finish is not
# unsafe by itself - they won't pass their own readiness probes
# against an unmigrated schema - but this script does not rely on
# that alone: it explicitly waits for both migration Jobs to report
# `condition=complete` before restarting/promoting the long-running
# services at all.
#
# Run from the repository root:
#   ./infra/scripts/deploy.sh
#
# Builds from the repository-root kustomization.yaml, NOT
# infra/kubernetes/kustomization.yaml - that file is intentionally no
# longer a valid entry point (see its own header comment: nesting it
# as a base under the root broke Kustomize's ConfigMap hash-suffix
# name-reference rewriting, confirmed empirically, not theoretically).
#
set -euo pipefail

NAMESPACE="medmatch"
WAIT_TIMEOUT="180s"
POSTGRES_WAIT_TIMEOUT="120s"

# -----------------------------------------------------------------------
# 0. Required tooling
# -----------------------------------------------------------------------
missing_tools=()
command -v kubectl >/dev/null 2>&1 || missing_tools+=("kubectl")

if [ "${#missing_tools[@]}" -gt 0 ]; then
    echo "!! Missing required tool(s): ${missing_tools[*]}" >&2
    echo "!! kubectl is required to apply, wait, and read logs from the cluster." >&2
    exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
    echo "-- Note: kustomize not found on PATH. Not required by this script" >&2
    echo "-- itself (it uses 'kubectl apply -k', which embeds its own" >&2
    echo "-- kustomize), but you should still run 'kustomize build .'" >&2
    echo "-- manually first to validate changes before deploying." >&2
fi

if ! command -v docker >/dev/null 2>&1; then
    echo "-- Note: docker not found. This script does not build images" >&2
    echo "-- itself. If ghcr.io/snehapriy958/medmatch-ai-service doesn't" >&2
    echo "-- yet contain alembic.ini/alembic/, build and push it first -" >&2
    echo "-- see the deployment runbook for the exact commands." >&2
fi

# -----------------------------------------------------------------------
# Secret must exist locally before anything is applied - never
# generated by this script, never populated with real values by it.
# -----------------------------------------------------------------------
if [ ! -f infra/kubernetes/secrets/secrets.yaml ]; then
    echo "!! infra/kubernetes/secrets/secrets.yaml does not exist." >&2
    echo "!! Create it locally from the template (never commit the result):" >&2
    echo "!!   cp infra/kubernetes/secrets/secrets.yaml.example infra/kubernetes/secrets/secrets.yaml" >&2
    echo "!!   # then edit secrets.yaml with real values" >&2
    exit 1
fi

# -----------------------------------------------------------------------
# Failure diagnostics helper. Prints Job status, pod status, and logs
# for a failed Job without masking the original failure or tripping
# `set -e` partway through (each diagnostic command is allowed to fail
# independently via `|| true` - a missing pod, for example, shouldn't
# hide the Job's own status output).
# -----------------------------------------------------------------------
print_job_failure_diagnostics() {
    local job_name="$1"
    echo "!! ---- ${job_name}: Job status ----" >&2
    kubectl describe job "${job_name}" -n "${NAMESPACE}" >&2 || true
    echo "!! ---- ${job_name}: Pod status ----" >&2
    kubectl get pods -n "${NAMESPACE}" -l "job-name=${job_name}" -o wide >&2 || true
    echo "!! ---- ${job_name}: Pod logs ----" >&2
    kubectl logs -n "${NAMESPACE}" -l "job-name=${job_name}" --all-containers --tail=200 >&2 || true
    echo "!! -----------------------------------" >&2
}

print_rollout_failure_diagnostics() {
    local deployment_name="$1"
    echo "!! ---- ${deployment_name}: rollout status ----" >&2
    kubectl rollout status "deployment/${deployment_name}" -n "${NAMESPACE}" >&2 || true
    echo "!! ---- ${deployment_name}: pod status ----" >&2
    kubectl get pods -n "${NAMESPACE}" -l "app=medmatch,component=${deployment_name}" -o wide >&2 || true
    echo "!! ---- ${deployment_name}: pod logs (last 100 lines) ----" >&2
    kubectl logs -n "${NAMESPACE}" -l "app=medmatch,component=${deployment_name}" --all-containers --tail=100 >&2 || true
    echo "!! -----------------------------------" >&2
}

# -----------------------------------------------------------------------
# 1. Apply the full stack (namespace, ConfigMap, Secret, PostgreSQL,
# Redis, migration Jobs, application Deployments) - see design note
# above for why this is one pass rather than several ordered file
# applies.
# -----------------------------------------------------------------------
echo "==> [1/6] Applying full manifest set (kubectl apply -k .)"
kubectl apply -k .

# -----------------------------------------------------------------------
# 2. PostgreSQL readiness
# -----------------------------------------------------------------------
echo "==> [2/6] Waiting for PostgreSQL readiness (timeout ${POSTGRES_WAIT_TIMEOUT})"
# Uses the StatefulSet's own existing pg_isready readinessProbe
# (infra/kubernetes/postgres/postgres-statefulset.yaml) rather than
# duplicating that check here or inside the migration Jobs - smallest
# reliable option, bounded by a timeout, not an infinite wait.
if ! kubectl wait --for=condition=Ready pod -l component=postgres \
        -n "${NAMESPACE}" --timeout "${POSTGRES_WAIT_TIMEOUT}"; then
    echo "!! PostgreSQL did not become ready in time. Aborting deploy." >&2
    kubectl get pods -n "${NAMESPACE}" -l component=postgres -o wide >&2 || true
    kubectl describe pod -n "${NAMESPACE}" -l component=postgres >&2 || true
    exit 1
fi

# -----------------------------------------------------------------------
# 3. Force a fresh migration run. Jobs are immutable once created, so
# re-applying the same completed Job is a no-op - delete first, then
# re-apply the full stack again, which recreates just the deleted
# Jobs (everything else is already up to date and unaffected).
# -----------------------------------------------------------------------
echo "==> [3/6] Re-running migration Jobs (delete any previous run, re-apply)"
kubectl delete job auth-migrate ai-migrate -n "${NAMESPACE}" --ignore-not-found
kubectl apply -k .

echo "==> [4/6] Waiting for auth-migrate to complete (timeout ${WAIT_TIMEOUT})"
if ! kubectl wait --for=condition=complete job/auth-migrate \
        --namespace "${NAMESPACE}" --timeout "${WAIT_TIMEOUT}"; then
    echo "!! auth-migrate did NOT complete successfully. Aborting deploy." >&2
    print_job_failure_diagnostics "auth-migrate"
    exit 1
fi

echo "==> [5/6] Waiting for ai-migrate to complete (timeout ${WAIT_TIMEOUT})"
if ! kubectl wait --for=condition=complete job/ai-migrate \
        --namespace "${NAMESPACE}" --timeout "${WAIT_TIMEOUT}"; then
    echo "!! ai-migrate did NOT complete successfully. Aborting deploy." >&2
    print_job_failure_diagnostics "ai-migrate"
    exit 1
fi

# -----------------------------------------------------------------------
# 4. Long-running services - only restarted/promoted now, after both
# migrations succeed.
# -----------------------------------------------------------------------
echo "==> [6/6] Both migrations succeeded. Rolling out long-running services."
kubectl rollout restart deployment/auth-service -n "${NAMESPACE}"
kubectl rollout restart deployment/ai-service -n "${NAMESPACE}"
kubectl rollout restart deployment/worker -n "${NAMESPACE}"

for svc in auth-service ai-service worker; do
    if ! kubectl rollout status "deployment/${svc}" -n "${NAMESPACE}" --timeout "${WAIT_TIMEOUT}"; then
        echo "!! Rollout of deployment/${svc} did NOT succeed. Aborting deploy." >&2
        print_rollout_failure_diagnostics "${svc}"
        exit 1
    fi
done

echo "==> Deploy complete."
