import hashlib


class CacheKeys:
    """
    Utility class for generating Redis cache keys.
    """

    # Increment this whenever retrieval logic changes in a way
    # that can alter the returned candidates.
    RETRIEVAL_VERSION = "v3-condition-filter"

    @staticmethod
    def _hash(value: str) -> str:
        """
        Generate a SHA-256 hash for cache keys.
        """

        return hashlib.sha256(
            value.encode("utf-8")
        ).hexdigest()

    @staticmethod
    def embedding(text: str) -> str:
        """
        Generate a cache key for text embeddings.
        """

        return f"embedding:{CacheKeys._hash(text)}"

    @staticmethod
    def retrieval(
        patient_note: str,
        top_k: int,
    ) -> str:
        """
        Generate a tenant-isolated, versioned cache key
        for retrieval results.

        The retrieval version ensures that changes to the
        retrieval/filtering algorithm do not reuse stale
        results generated by an older implementation.
        """

        return (
            f"retrieval:"
            f"{CacheKeys.RETRIEVAL_VERSION}:"
            f"{CacheKeys._hash(patient_note)}:"
            f"{top_k}"
        )

    @staticmethod
    def llm(prompt: str) -> str:
        """
        Generate a cache key for LLM responses.
        """

        return f"llm:{CacheKeys._hash(prompt)}"

    @staticmethod
    def match(
        patient_id: int,
        trial_id: int,
    ) -> str:
        """
        Generate a cache key for complete trial matching results.
        """

        return f"match:{patient_id}:{trial_id}"