[mypy]
python_version = 3.13

plugins = pydantic.mypy

ignore_missing_imports = False

warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True

[mypy-fitz]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True